# fPho Configuration file

# ----------------
# --- Overall ----
logging:
  True

# -----------------------
# --- Filters being run ---
bandlist:
 - F090W
 - F115W
 - F150W
 - F200W
 - F277W
 - F335M
 - F356W
 - F410M
 - F444W

# ------------------------------
# --- photometric zeropoints ---
# Only required if images do not have the ABMAG keyword and are not already in nJy/pix
#zeropoints:
#  F090W: 24.04.....

# ----------------------------
# --- exposure backgrounds ---
# name of dictionary and keyword to add to header
tweak_background:
  tweakbg
# in nJy/pix, to be subtracted from individual exposures
tweakbg:
   F090W: 0.0125
   F115W: 0.0125
   F150W: 0.0125
   F200W: 0.0125
   F277W: 0.0125
   F335M: 0.0175
   F356W: 0.0125
   F410M: 0.0175
   F444W: 0.0125

# ---------------------
# --- preprocessing ---
original_images:
  $PROJECT_DIR/data/images/mosaics/*final/*[WM].fits
cutID:
  jades-morph-mosaic
frames_directory:  # full path (optional, for preprocessing)
  $PROJECT_DIR/data/cutouts
frame_search_pattern:
  jades-morph-mosaic-??-??_*[WM].fits
max_snr:
  0
do_fluxcal:  # whether to flux calibrate the images using ABMAG keyword
  0
bitmask: # integer corresponding to the bits of the mask image that constitue "bad" pixels.
  1
detection_catalog: # full path to input catalog
  $PROJECT_DIR/data/catalogs/detection_table_v0.5.fits

# ----------------------------
# --- Input data locations ---
raw_catalog:
  $PROJECT_DIR/data/catalogs/jades-morph_v0.fits

store_directory:
  $PROJECT_DIR/data/stores
splinedatafile:
  $PROJECT_DIR/data/stores/sersic_mog_model.smooth=0.0150.h5
pixelstorefile:
  pixels_jades-morph-mosaic.h5
metastorefile:
  meta_jades-morph-mosaic.json
psfstorefile:
  psf_jades_ng4.h5

# ------------------------
# --- Output locations
outbase:
  ../output/test
scene_catalog:
  outscene.fits

# -----------------------
# --- Bounds & Priors ---
minflux:

bounds_kwargs:
  n_sig_flux: 10.0  # Nsigma/snr at flux = 1/nJy
  sqrtq_range: # range of sqrt(b/a)
    - 0.4
    - 1.0
  pa_range:  # range of pa, radians
    - -2.0
    - 2.0
  n_pix: # number of pixels for dRA, dDec
    2
  pixscale: # pixelscale for dRA, dDdec
    0.03

# ------------------------
# --- Data Types/Sizes ---
pix_dtype:
  float32
meta_dtype:
  float32
super_pixel_size:  # number of pixels along one side of a superpixel
  8
nside_full:  # number of pixels along one side of a square input frame
 - 2048
 - 2048

# -----------------------
# --- Patch Generation ---
max_active_fraction:
  0.1
maxactive_per_patch:
  15
patch_maxradius:  # in arcsec
  3
patch_minradius:
  2
target_niter:
  256
ntry_checkout:
  1000
buffer_size:
  5e7

# -----------------------
# --- HMC parameters ---
max_treedepth:
  9
sampling_draws:
  256
warmup:
 - 128
full_cov:
  True
